### ISSUE TITLE
Incorrect labeling of J16 Power connector

### ISSUE THREAD

**Issue by kpishere** [ayourk/Nabu-PC#1]
The document Nabu_Computer_Technical_Manual_by_MJP-compressed.pdf on the last page appears to have incorrect labeling of the J16 connector.  With Voltmeter, I read the following.

![Screen Shot 2023-03-23 at 6 09 54 PM](https://user-images.githubusercontent.com/25204173/227377784-bb1a2ae1-4bb8-4027-9562-96b2c1d9c804.png)

Pin 4, I'd expect to be -12V but it does not appear to work.  Anybody else seeing that?

**Comment by ayourk** [comment]
> The document Nabu_Computer_Technical_Manual_by_MJP-compressed.pdf on the last page appears to have incorrect labeling of the J16 connector. With Voltmeter, I read the following.
> 
> ![Screen Shot 2023-03-23 at 6 09 54 PM](https://user-images.githubusercontent.com/25204173/227377784-bb1a2ae1-4bb8-4027-9562-96b2c1d9c804.png)
> 
> Pin 4, I'd expect to be -12V but it does not appear to work. Anybody else seeing that?

That sounds about right.  There are modifications that are typically made to the developer machines using a fat bodge wire on the bottom of the main board to fix this: https://www.youtube.com/watch?v=i-kjwh8fhdk

**Comment by kpishere** [comment]
Thanks!
